[package]
name = "greed"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
engine = { path = "../engine", version = "0.1.0" }
tracing.workspace = true